### ISSUE TITLE
Implement API request of 2nd group

### ISSUE THREAD

**Issue by juansedo** [sanhidalgoo/heap-group#49]
Description
=======
Talk to them and ask for an API guide.
![image](https://user-images.githubusercontent.com/52968530/168331705-3d4274fa-392a-47cb-a706-a83d4558a40a.png)

**Comment by sanhidalgoo** [comment]
@juansedo 
LA ruta para consumir es la siguiente

http://34.122.198.163/public/api/computers

La positiva mi amigo! : )
